name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          # Set the CI environment variable to false to prevent warnings from being treated as errors
          echo "CI=false" >> $GITHUB_ENV
          npm run build

      - name: Deploy
        run: |
          git config --global user.name 'theo'
          git config --global user.email 'theocastillo@yahoo.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          # Include the deployment steps here
          npm run deploy
